[workspace]
members = ["packages/*", "contracts/*"]
version = "0.10.3"


[profile.release.package.cw-band]
codegen-units = 1
incremental = false


[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
