#!/usr/bin/env python3
import requests
import sys

PRICE_URL = "https://api.coingecko.com/api/v3/simple/price"


def adjust_rounding(data):
    if data < 1:
        return round(data, 8)
    elif data < 10:
        return round(data, 6)
    else:
        return round(data, 4)


def main(symbols):
    SUPPORT_SLUGS = {
        "BTG": "bitcoin-gold",
        "BZRX": "bzx-protocol",
        "SRM": "serum",
        "SNT": "status",
        "SOL": "solana",
        "CKB": "nervos-network",
        "BNT": "bancor",
        "CRV": "curve-dao-token",
        "MANA": "decentraland",
        "KAVA": "kava",
        "MATIC": "matic-network",
        "TRB": "tellor",
        "REP": "augur",
        "FTM": "fantom",
        "TOMO": "tomochain",
        "ONE": "harmony",
        "WNXM": "wrapped-nxm",
        "PAXG": "pax-gold",
        "WAN": "wanchain",
        "SUSD": "nusd",
        "RLC": "iexec-rlc",
        "FNX": "finnexus",
        "WBTC": "wrapped-bitcoin",
        "DIA": "dia-data",
        "BTM": "bytom",
        "IOTX": "iotex",
        "FET": "fetch-ai",
        "JST": "just",
        "KMD": "komodo",
        "BTS": "bitshares",
        "QKC": "quark-chain",
        "YAMV2": "yam-v2",
        "AKRO": "akropolis",
        "KAI": "kardiachain",
        "OGN": "origin-protocol",
        "WRX": "wazirx",
        "KDA": "kadena",
        "FOR": "force-protocol",
        "AST": "airswap",
        "STORJ": "storj",
        "2KEY": "2key",
        "ABYSS": "the-abyss",
        "BLZ": "bluzelle",
        "BTU": "btu-protocol",
        "CND": "cindicator",
        "CVC": "civic",
        "DGX": "digix-gold",
        "ELF": "aelf",
        "EQUAD": "quadrant-protocol",
        "EURS": "stasis-eurs",
        "FXC": "futurexcrypto",
        "GDC": "global-digital-content",
        "GEN": "daostack",
        "GHT": "global-human-trust",
        "GNO": "gnosis",
        "GVT": "genesis-vision",
        "IOST": "iostoken",
        "KEY": "selfkey",
        "LOOM": "loom-network",
        "MET": "metronome",
        "MLN": "melon",
        "MTL": "metal",
        "MYB": "mybit-token",
        "NEXXO": "nexxo",
        "NPXS": "pundi-x",
        "OST": "simple-token",
        "PAY": "tenx",
        "PBTC": "ptokens-btc",
        "PLR": "pillar",
        "PLTC": "ptokens-ltc",
        "PNK": "kleros",
        "PNT": "pnetwork",
        "POLY": "polymath",
        "POWR": "power-ledger",
        "QNT": "quant-network",
        "RAE": "rae-token",
        "REQ": "request-network",
        "RSV": "reserve",
        "SAN": "santiment-network-token",
        "SPIKE": "spiking",
        "SPN": "sapien",
        "STMX": "storm",
        "TKN": "tokencard",
        "TKX": "tokenize-xchange",
        "TRYB": "bilira",
        "UBT": "unibright",
        "UPP": "sentinel-protocol",
        "USDS": "stableusd",
        "VIDT": "v-id-blockchain",
        "CAKE": "pancakeswap-token",
        "CREAM": "cream-2",
        "UNI": "uniswap",
        "FIL": "filecoin",
        "ALPHA": "alpha-finance",
        "TWT": "trust-wallet-token",
        "UOS": "ultra",
        "HNT": "helium",
        "HOT": "holotoken",
        "ORN": "orion-protocol",
        "MFG": "smart-mfg",
        "SXP": "swipe",
        "RENBTC": "renbtc",
        "BNB": "binancecoin",
        "ETH": "ethereum",
        "BTC": "bitcoin",
        "LINA": "linear",
        "XVS": "venus",
        "BSV": "bitcoin-cash-sv",
        "CRO": "crypto-com-chain",
        "XMR": "monero",
        "OKB": "okb",
        "NEO": "neo",
        "XEM": "nem",
        "LEO": "leo-token",
        "HT": "huobi-token",
        "VET": "vechain",
        "MIOTA": "iota",
        "LEND": "ethlend",
        "SNX": "havven",
        "DASH": "dash",
        "COMP": "compound-governance-token",
        "ZEC": "zcash",
        "ETC": "ethereum-classic",
        "OMG": "omisego",
        "MKR": "maker",
        "ONT": "ontology",
        "NXM": "nxm",
        "AMPL": "ampleforth",
        "BAT": "basic-attention-token",
        "THETA": "theta-token",
        "REN": "republic-protocol",
        "ZRX": "0x",
        "ALGO": "algorand",
        "FTT": "ftx-token",
        "DOGE": "dogecoin",
        "KSM": "kusama",
        "WAVES": "waves",
        "EWT": "energy-web-token",
        "DGB": "digibyte",
        "KNC": "kyber-network-crystal",
        "ICX": "icon",
        "TUSD": "true-usd",
        "SUSHI": "sushi",
        "BTT": "bittorrent-2",
        "EGLD": "elrond-erd-2",
        "ANT": "aragon",
        "NMR": "numeraire",
        "USDP": "paxos-standard",
        "LSK": "lisk",
        "BCH": "bitcoin-cash",
        "LTC": "litecoin",
        "USDT": "tether",
        "BAND": "band-protocol",
        "DAI": "dai",
        "EOS": "eos",
        "XTZ": "tezos",
        "ATOM": "cosmos",
        "USDC": "usd-coin",
        "TRX": "tron",
        "XRP": "ripple",
        "LINK": "chainlink",
        "DOT": "polkadot",
        "YFI": "yearn-finance",
        "XLM": "stellar",
        "ADA": "cardano",
        "BUSD": "binance-usd",
        "LRC": "loopring",
        "HBAR": "hedera-hashgraph",
        "BAL": "balancer",
        "RUNE": "thorchain",
        "YFII": "yfii-finance",
        "LUNA": "terra-luna",
        "DCR": "decred",
        "SC": "siacoin",
        "STX": "blockstack",
        "ENJ": "enjincoin",
        "OCEAN": "ocean-protocol",
        "RSR": "reserve-rights-token",
        "FRAX": "frax",
        "OXT": "orchid-protocol",
        "XHV": "haven",
        "AAVE": "aave",
        "HEGIC": "hegic",
        "SFI": "saffron-finance",
        "KP3R": "keep3rv1",
        "RVN": "ravencoin",
        "SCRT": "secret",
        "STRK": "strike",
        "INDEX": "index-cooperative",
        "PERP": "perpetual-protocol",
        "DPI": "defipulse-index",
        "ANC": "anchor-protocol",
        "MIR": "mirror-protocol",
        "VAI": "vai",
        "UMA": "uma",
        "CELO": "celo",
        "QTUM": "qtum",
        "ZIL": "zilliqa",
        "MVL": "mass-vehicle-ledger",
        "ARPA": "arpa-chain",
        "AUTO": "auto",
        "UST": "terrausd",
        "AETH": "ankreth",
        "DEFI++": "piedao-defi",
        "ALCX": "alchemix",
        "OHM": "olympus",
        "MIM": "magic-internet-money",
        "MOVR": "moonriver",
        "AVAX": "avalanche-2",
        "INJ": "injective-protocol",
        "JOE": "joe",
        "ORCA": "orca",
        "BEL": "bella-protocol",
        "ORC": "orbit-chain",
        "SHIB": "shiba-inu",
        "AXS": "axie-infinity",
        "ROSE": "oasis-network",
        "C98": "coin98",
        "CUSD": "celo-dollar",
        "GRT": "the-graph",
        "NEAR": "near",
        "DYDX": "dydx",
        "IMX": "immutable-x",
        "BORA": "bora",
        "SKL": "skale",
        # Extra token
        "BTCB": "bitcoin-bep2",
        "BETH": "binance-eth",
    }

    slugs = []
    for symbol in symbols:
        if symbol not in SUPPORT_SLUGS:
            raise Exception(f"Unsupported {symbol} symbol")
        slugs.append(SUPPORT_SLUGS[symbol])
    prices = requests.get(
        PRICE_URL,
        params={"ids": ",".join(slugs), "vs_currencies": "USD"},
    ).json()
    result = [(px["usd"], slug) for slug in slugs for (key, px) in list(prices.items()) if slug == key]
    prices = [str(adjust_rounding(px[0])) for px in result]
    if len(prices) != len(symbols):
        raise Exception("PRICES_AND_SYMBOL_LEN_NOT_MATCH")
    return ",".join(prices)


if __name__ == "__main__":
    try:
        print(main([*sys.argv[1:]]))
    except Exception as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)

